cleaner_dict = {"let's": 'let us', 
        "let’s": 'let us', "c'mon": 'come on',
        "c’mon": 'come on',
        "there’s": 'there is',
        "there's": 'there is',
        "you're": 'you are',
        "you’re": 'you are',
        "we're": 'we are',
        "we’re": 'we are',
        "i'm": 'i am',
        "i’m": 'i am',
        "y'": 'you', 
        "y’": 'you',
        "how'd": 'how did', 
        "how’d": 'how did',
        "\'ll": ' will', 
        "\’t": ' not',
        "\'t": ' not', 
        "\'s": '  is',
        "\’s": '  is',
        "\'re": '  are',
        "\’re": '  are',
        "\'": ' ', 
        '\"': ' '
        '-': ' ', 
        'pheebs': 'phoebe',
        'wasn': 'was not',
        'noo': 'no',
        "didn": 'did'}